# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 CERN.
# Copyright (C) 2025 Graz University of Technology.
# Copyright (C) 2025 KTH Royal Institute §of Technology.
#
# Invenio-stats is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: i18n:push translations
on: workflow_dispatch # manually trigger

jobs:
  i18n-extract:
    uses: inveniosoftware/invenio-i18n/.github/workflows/i18n-push-base.yml@master
    with:
      extract-backend: true
    secrets: inherit
