# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 CERN.
# Copyright (C) 2025 Graz §University of Technology.
# Copyright (C) 2025 KTH Royal Institute of Technology.
#
# Invenio-stats is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches:
      - master
      - maint-**
  pull_request:
    branches:
      - master
      - maint-**
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Python:
    uses: inveniosoftware/workflows/.github/workflows/tests-python.yml@master
